### ISSUE TITLE
Add `consult-notes-search-in-all-notes` as a local source, or any configurable ripgrep local search.

### ISSUE THREAD

**Issue by chemtov** [armindarvish/consult-web#28]
Hi,

thanks again for this project and the very nice write up associated with it.

**Is your feature request related to a problem? Please describe.**

I want to be able to search local notes directories which are not necessarily associated with denote or org-roam.

**Describe the solution you'd like**

Ideally the results from `consult-notes-search-in-all-notes` could be a source.  The alternative would be a to be able to have a `(consult-ripgrep sources)` where `sources` is a list of directories.

Regards,

**Comment by armindarvish** [comment]
@chemtov, The feature you are requesting would indeed be useful. We need a general solution so we can combine any sync and async sources in a multi-source search. There is already some effort in the async branch to support this, and so far we can combine sync and async sources that use elisp but not yet an async source that uses a shell command (like ripgrep). This requires some more hacking (and reinventing) of the consult-async process, and will take some time before I can support this in the package.
